---
# Hubspot for Greenpeace

pipeline_name: Hubspot for Greenpeace

nodes:
  get_environment_variables:
    class: GetEnvironmentVariables
    summary: Gets all the necessary environment variables
    options:
      environment_variables:
        - HUBSPOT_API_KEY
        - HUBSPOT_USER_ID
  
  get_unmatched_emails:
    class: CivisToCSV
    summary: Executes SQL to find missing email addresses
    options:
      sql: "SELECT DISTINCT recipient FROM gpbr_staging.email_raw WHERE email_raw.recipient NOT IN (SELECT email FROM gpbr_staging.vid_email);"
      database: Greenpeace
      returned_columns:
        - recipient

  batch_unmatched_emails:
    class: BatchMessages
    summary: Batches the emails into groups of fifty
    options:
      key: recipient
      batch_size: 500
      output_key: email_address_list
  
  
  hubspot_engagements_paginator:
    class: HttpGetRequestPaginator
    options:
      pagination_get_request_key: offset
      output_key: hubspot_engagements_paginator
      endpoint_template: "https://api.hubapi.com/engagements/v1/engagements/paged?hapikey={HUBSPOT_API_KEY}&count={limit}&offset={offset}"
      additional_data_key: hasMore
      pagination_key: offset
      endpoint_dict:
        limit: 100
  
  hubspot_contacts_paginator:
    class: HttpGetRequestPaginator
    options:
      pagination_get_request_key: vid_offset
      output_key: hubspot_contacts_paginator
      endpoint_template: "https://api.hubapi.com/contacts/v1/lists/all/contacts/all?hapikey={HUBSPOT_API_KEY}&count={limit}&vidOffset={vid_offset}"
      additional_data_key: has-more
      pagination_key: vid-offset
      endpoint_dict:
        limit: 100


  

  serialize_contacts:
    class: Serializer
    options:
      retain_input: true
      key: [hubspot_contacts_paginator, contacts]
      output_key: contact_row

  batch_contacts:
    class: BatchMessages
    options:
      key: contact_row
      batch_size: 1000
      output_key: contact_rows

  hubspot_forms_paginator:
    class: HttpGetRequest
    options:
      output_key: hubspot_forms_paginator
      endpoint_template: "https://api.hubapi.com/forms/v2/forms?hapikey={HUBSPOT_API_KEY}"







  hubspot_email_events_paginator:
    class: HttpGetRequestPaginator
    options:
      output_key: hubspot_email_events_paginator
      pagination_get_request_key: offset
      endpoint_template: "https://api.hubapi.com/email/public/v1/events?hapikey={HUBSPOT_API_KEY}&startTimestamp={start_timestamp}&endTimestamp={end_timestamp}&limit={limit}&offset={offset}"
      additional_data_key: hasMore
      pagination_key: offset
      endpoint_dict:
        start_timestamp: {{ nanostream__utils__helpers__two_weeks_ago }}
        end_timestamp: {{ nanostream__utils__helpers__now_milliseconds }}
        limit: 100
  
  send_email_to_redshift:
    class: SendToCivis
    options:
      dummy_run: false
      schema: gpbr_staging
      database: Greenpeace
      table_name: email_raw
      block: false
      input_message_keypath: [hubspot_email_events_paginator, events]
      existing_table_rows: append
      max_errors: 0
      output_key: send_email_to_redshift
      remap:
        email_campaign_id: [emailCampaignId]
        app_id: [appId]
        app_name: [appName]
        smtp_id: [smtpId]
        created: [created]
        sent_by_id: [sentBy, id]
        sent_by_created: [sentBy, created]
        location_state: [location, state]
        location_country: [location, country]
        location_city: [location, city]
        device_type: [deviceType]
        recipient: [recipient]
        browser_name: [browser, name]
        browser_type: [browser, type]
        browser_producer_url: [browser, producerUrl]
        browser_family: [browser, family]
        browser_url: [browser, url]
        browser_producer: [browser, producer]
        type: [type]
        ip_address: [ipAddress]
        duration: [duration]
        filtered_event: [filteredEvent]
        id: [id]
        portal_id: [portalId]
      columns:
        - filtered_event
        - id
        - location_state
        - created
        - device_type
        - sent_by_id
        - browser_producer
        - duration
        - ip_address
        - app_id
        - browser_producer_url
        - location_country
        - browser_family
        - browser_url
        - app_name
        - type
        - location_city
        - sent_by_created
        - browser_name
        - recipient
        - email_campaign_id
        - smtp_id
        - browser_type
        - portal_id
          
  email_printer:
    class: PrinterOfThings
    options:
      disable: true
      prepend: email_printer
  
  forms_printer:
    class: PrinterOfThings
    options:
      disable: true
      prepend: forms_printer
  
  engagements_printer:
    class: PrinterOfThings
    options:
      disable: true
      prepend: engagements_printer_output
  
  contacts_printer:
    class: PrinterOfThings
    options:
      disable: true
      prepend: contacts_printer_output
  
  email_printer:
    class: PrinterOfThings
    options:
      disable: true
      prepend: email_printer_output

  send_contacts_to_redshift:
    class: SendToCivis
    options:
      dummy_run: false
      schema: gpbr_staging
      database: Greenpeace
      table_name: contacts_raw
      block: false
      existing_table_rows: append
      input_message_keypath: [contact_rows]
      max_errors: 0
      output_key: send_contacts_to_redshift
      remap:
        added_at: [addedAt]
        canonical_vid: [canonical-vid]
        profile_token: [profile-token]
        vid: [vid]
        profile_url: [profile-url]
        is_contact: [is-contact]
        portal_id: [portal-id]
        last_modified_date: [properties, lastmodifieddate, value]
        first_name: [properties, firstname, value]
        last_name: [properties, lastname, value]
        saved_at_timestamp: [saved-at-timestamp]
      columns:
        - profile_url
        - first_name
        - canonical_vid
        - is_contact
        - saved_at_timestamp
        - profile_token
        - last_modified_date
        - portal_id
        - added_at
        - vid

  generate_email_api_query:
    class: SimpleTransforms
    options:
      retain_input: false
      transform_mapping:
        - target_function: hubspot__hi
          path: [email_address_list]

  generic_printer:
    class: PrinterOfThings
    options:
      disable: false
      prepend: HiThere

  get_contact_for_email:
    class: HttpGetRequest
    options:
      retain_input: false
      output_key: contact_information
      endpoint_template: "https://api.hubapi.com/contacts/v1/contact/emails/batch/?{email_address_list}&property=profile-token&hapikey={HUBSPOT_API_KEY}"

  aggregate_identities:
    class: AggregateValues
    options:
      tail_path: [contact_information]
      output_key: identities_list
      values: true
  
  serialize_identities:
    class: Serializer
    options:
      retain_input: false
      key: identities_list
      output_key: identity_dictionary

  collect_vid_list:
    class: AggregateValues
    options:
        tail_path: [vid]
        output_key: vid_list

  find_email_address:
    class: SimpleTransforms
    options:
      retain_input: false
      transform_mapping:
        - target_function: hubspot__collect_email
          path: [identity_dictionary]
  
  serialize_vid_list:
    class: Serializer
    options:
      retain_input: true
      key: vid_list
      output_key: vid
  
  make_vid_email_row:
    class: Remapper
    options:
      retain_input: true
      mapping:
        vid: vid
        email: [identity_dictionary, email_address]
      output_key: vid_email_row
  
  batch_vid_email_rows: 
    class: BatchMessages
    options:
      key: vid_email_row
      batch_size: 1000
      output_key: row_list
  
  send_vid_email_to_civis:
    class: SendToCivis
    options:
      dummy_run: false
      schema: gpbr_staging
      database: Greenpeace
      table_name: vid_email
      block: false
      input_message_keypath: [row_list]
      existing_table_rows: append
      max_errors: 0
      output_key: send_vid_email_to_civis
      columns:
        - vid
        - email
  
  batch_identity_dictionaries:
    class: BatchMessages
    options:
      key: identity_dictionary
      batch_size: 50
      output_key: row_list
  
  hubspot_recent_contacts_paginator:
    class: HttpGetRequestPaginator
    options:
      pagination_get_request_key: vid_offset
      output_key: hubspot_recent_contacts_paginator
      endpoint_template: "https://api.hubapi.com/contacts/v1/lists/all/contacts/all?hapikey={HUBSPOT_API_KEY}&vidOffset={vid_offset}&limit={limit}"
      endpoint_template_bak: "https://api.hubapi.com/contacts/v1/lists/recently_updated/contacts/recent?hapikey={HUBSPOT_API_KEY}&vidOffset={vid_offset}"
      additional_data_key: has-more
      pagination_key: vid-offset
      endpoint_dict:
        limit: 100
  
  serialize_recent_contacts:
    class: Serializer
    options:
      retain_input: true
      key: [hubspot_recent_contacts_paginator, contacts]
      output_key: contact

  serialize_form_submissions:
    class: Serializer
    options:
      retain_input: true
      key: [contact, form-submissions]
      output_key: serialized_form_submission

  recent_contacts_printer:
    class: PrinterOfThings
    options:
      disable: false
      pretty: true
      prepend: recent_contacts_printer
  
  collect_form_signature_record:
    class: Remapper
    options:
      retain_input: true
      mapping:
        canonical_vid: [contact, canonical-vid]
        profile_token: [contact, profile-token]
        form_id: [serialized_form_submission, form-id]
        conversion_id: [serialized_form_submission, conversion-id]
        timestamp: [serialized_form_submission, timestamp]
      output_key: signature_event
  
  batch_signature_events: 
    class: BatchMessages
    options:
      key: signature_event
      batch_size: 250
      output_key: row_list

  send_signature_events_to_civis:
    class: SendToCivis
    options:
      dummy_run: false
      schema: gpbr_staging
      database: Greenpeace
      table_name: signature_events
      block: false
      input_message_keypath: [row_list]
      existing_table_rows: append
      max_errors: 0
      output_key: send_signature_events_to_civis
      columns:
        - canonical_vid
        - conversion_id
        - profile_token
        - form_id
        - timestamp

edges:
  - source: get_environment_variables
    target: hubspot_recent_contacts_paginator
  - source: hubspot_recent_contacts_paginator
    target: serialize_recent_contacts
  - source: serialize_recent_contacts
    target: serialize_form_submissions
  - source: serialize_form_submissions
    target: collect_form_signature_record
  - source: collect_form_signature_record
    target: batch_signature_events
  - source: batch_signature_events
    target: send_signature_events_to_civis
  - source: send_signature_events_to_civis
    target: recent_contacts_printer
  - source: get_environment_variables
    target: hubspot_email_events_paginator
  - source: hubspot_email_events_paginator
    target: send_email_to_redshift
  - source: send_email_to_redshift
    target: email_printer
  - source: get_environment_variables
    target: hubspot_forms_paginator
  - source: hubspot_forms_paginator
    target: forms_printer
  - source: get_environment_variables
    target: hubspot_engagements_paginator
  - source: hubspot_engagements_paginator
    target: engagements_printer
  - source: get_environment_variables
    target: hubspot_contacts_paginator
  - source: hubspot_contacts_paginator
    target: serialize_contacts
  - source: serialize_contacts
    target: batch_contacts
  - source: batch_contacts
    target: send_contacts_to_redshift
  - source: send_contacts_to_redshift
    target: contacts_printer
  - source: get_environment_variables
    target: get_unmatched_emails
  - source: get_unmatched_emails
    target: batch_unmatched_emails
  - source: batch_unmatched_emails
    target: generate_email_api_query
  - source: generate_email_api_query
    target: get_contact_for_email
  - source: get_contact_for_email
    target: aggregate_identities
  - source: aggregate_identities
    target: serialize_identities
  - source: serialize_identities
    target: collect_vid_list
  - source: collect_vid_list
    target: find_email_address
  - source: find_email_address
    target: serialize_vid_list
  - source: serialize_vid_list
    target: make_vid_email_row
  - source: make_vid_email_row
    target: batch_vid_email_rows
  - source: batch_vid_email_rows
    target: send_vid_email_to_civis
  - source: send_vid_email_to_civis
    target: generic_printer
