nodes:
  read_departments:
    class: StreamMySQLTable
    summary: Stream rows from the MySQL table
    options:
      database: employees
      user: zac
      host: localhost
      port: 1500
      password: imadfs618
      table: departments
  departments_to_graph:
    class: GraphNode
    options:
      config_file: departments_table.yaml
      input_table: departments
  printer:
    class: PrinterOfThings
  to_neo4j:
    class: Neo4JExecutor
    options:
      uri: bolt://localhost:7687
      user: neo4j
      password: imadfs618

paths:
  -
    - read_departments
    - printer
    - departments_to_graph
    - to_neo4j
