nodes:
  read_dept_manager:
    class: StreamMySQLTable
    summary: Stream rows from the MySQL table
    options:
      database: employees
      user: zac
      host: localhost
      port: 1500
      password: imadfs618
      table: dept_manager
  dept_manager_to_graph:
    class: GraphNode
    options:
      config_file: dept_manager_table.yaml
      input_table: dept_manager
  printer:
    class: PrinterOfThings
  to_neo4j:
    class: Neo4JExecutor
    options:
      uri: bolt://localhost:7687
      user: neo4j
      password: imadfs618

paths:
  -
    - read_dept_manager
    - printer
    - dept_manager_to_graph
    - to_neo4j
